### ISSUE TITLE
module 'numpy' has no attribute 'object'.

### ISSUE THREAD

**Issue by GallVp** [cytham/nanovar#67]
Thank you for your excellent tool.

Using the 1.5.0--py39hf95cd2a_0 version from biocontainers (https://quay.io/repository/biocontainers/nanovar?tab=tags) gives the following error. This is likely due to the updated numpy (1.20) being used by the biocontainer as allowed by the setup constraints (numpy>=1.17.3).

/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "/usr/local/bin/nanovar", line 591, in <module>
    main()
  File "/usr/local/bin/nanovar", line 342, in main
    from nanovar.nv_characterize import VariantDetect
  File "/usr/local/lib/python3.8/site-packages/nanovar/nv_characterize.py", line 30, in <module>
    from nanovar.nv_nn import inference, svread_ovl
  File "/usr/local/lib/python3.8/site-packages/nanovar/nv_nn.py", line 26, in <module>
    from tensorflow.keras.models import load_model
  File "/usr/local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 46, in <module>
    from tensorflow.python import data
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/__init__.py", line 25, in <module>
    from tensorflow.python.data import experimental
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/experimental/__init__.py", line 96, in <module>
    from tensorflow.python.data.experimental import service
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/experimental/service/__init__.py", line 140, in <module>
    from tensorflow.python.data.experimental.ops.data_service_ops import distribute
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/data_service_ops.py", line 25, in <module>
    from tensorflow.python.data.experimental.ops import compression_ops
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/experimental/ops/compression_ops.py", line 20, in <module>
    from tensorflow.python.data.util import structure
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py", line 26, in <module>
    from tensorflow.python.data.util import nest
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 41, in <module>
    from tensorflow.python.framework import sparse_tensor as _sparse_tensor
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/sparse_tensor.py", line 29, in <module>
    from tensorflow.python.framework import constant_op
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py", line 29, in <module>
    from tensorflow.python.eager import execute
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 27, in <module>
    from tensorflow.python.framework import dtypes
  File "/usr/local/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/usr/local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by cytham** [comment]
Thanks for reporting this @GallVp, will fix this in v1.5.1. Thanks!

**Comment by GallVp** [comment]
Thank you @cytham 

For others:

This problem can also be solved by first installing the dependencies as follows:


```bash
pip3 install numpy==1.19.5 tensorflow-cpu==2.5.0 scipy biopython pybedtools matplotlib natsort progress pysam htmlark cytocad
cd nanovar && python3 setup.py install
```

**Comment by eesiribloom** [comment]
I am still getting this error with v1.5.1. 
I downloaded this container https://depot.galaxyproject.org/singularity/nanovar%3A1.5.1--py39hf95cd2a_0 for use with singularity

**Comment by cytham** [comment]
@eesiribloom Did you try just installing nanovar using pip?

**Comment by eesiribloom** [comment]
With pip install I get this error:
 Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ffixn8ea/scipy_152131ca7f1243aab1fb8e3739788438/setup.py", line 492, in <module>
          setup_package()
        File "/tmp/pip-install-ffixn8ea/scipy_152131ca7f1243aab1fb8e3739788438/setup.py", line 413, in setup_package
          write_version_py()
        File "/tmp/pip-install-ffixn8ea/scipy_152131ca7f1243aab1fb8e3739788438/setup.py", line 138, in write_version_py
          FULLVERSION, GIT_REVISION = get_version_info()
                                      ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-ffixn8ea/scipy_152131ca7f1243aab1fb8e3739788438/setup.py", line 114, in get_version_info
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by cytham** [comment]
What python version are you on? Could you please try on Python version 3.8 to 3.11.
